#!/bin/sh
# Generate a minimal self-contained TU that instantiates ONLY the 4 target
# mul_mat_vec_q kernels (Q4_K=12, Q6_K=14; ncols_dst=1; small_k=false, halve_iters=false).
# Slices exact line ranges from mmvq.cu so it stays faithful. Re-run if mmvq.cu changes.
set -e
SRC=../ggml/src/ggml-cuda/mmvq.cu
OUT=mmvq_probe.cu

sig='(const void*, const void*, const int32_t*, const ggml_cuda_mm_fusion_args_device, float*, const uint32_t, const uint3, const uint32_t, const uint32_t, const uint32_t, const uint3, const uint32_t, const uint32_t, const uint32_t, const uint3, const uint32_t, const uint32_t, const uint32_t, const uint32_t)'

{
  echo '// AUTO-GENERATED by gen_probe.sh - do NOT edit by hand.'
  echo '#include "common.cuh"'
  echo '#include "vecdotq.cuh"'
  echo '#include "unary.cuh"'
  echo '#include <cstdint>'
  echo '#include <type_traits>'
  echo
  sed -n '9,36p'   "$SRC"   # DGX prefetch helpers (guarded, NVIDIA-only)
  sed -n '38,122p' "$SRC"   # typedef, get_vec_dot_q_cuda, get_vdr_mmvq, enum, device get_device_table_id
  sed -n '436,581p' "$SRC"  # calc_nwarps, calc_rows_per_block
  sed -n '583,829p' "$SRC" | sed 's/^static __global__ void mul_mat_vec_q(/__global__ void mul_mat_vec_q(/'  # kernel (drop static so it can be instantiated)
  echo
  echo '// ---- explicit instantiations ----'
  for t in 12 14; do
    for f in true false; do
      echo "template __global__ void mul_mat_vec_q<(ggml_type)$t, 1, $f, false, false>$sig;"
    done
  done
} > "$OUT"
echo "wrote $OUT ($(wc -l < "$OUT") lines)"
